### ISSUE TITLE
[BUG] cannot read properties of undefined (reading 'translations')

### ISSUE THREAD

**Issue by madwichery** [twentytwokhz/language-translator#10]
Thank you for creating this amazing plugins.
It works for couple days and suddenly when i try to translate this popping up
`cannot read properties of undefined (reading 'translations')`

is it because i don't have the API key for the translation perhaps?

**Comment by fokewulf** [comment]
Hi Thank you for creating this amazing plugins.
But after i used for two weeks, today i have same problem

**Comment by martinopiaggi** [comment]
Hi, it's an amazing plugin but same problem too. It worked for a few days and then it started to give me this error. I use it with a custom shortcut 'insert translation' from italian to english. Thanks.

**Comment by Medenor** [comment]
Same issue since a couple of days. Changing languages or translator does not solve it.

**Comment by mateusfonseca01** [comment]
just intalled the plug in but had the same problem

**Comment by CodeTorom** [comment]
same issue, has anyone find out what's causing this?

**Comment by twentytwokhz** [comment]
Investigated the issue but was not able to reproduce. I added some exception handling, but I assume it has to do with the amount of translation text that is handled and the quota on the API.
Measures have been added to **identify** this on the server side and **inform the user** on the frontend side.

Let me know if it is still reproducible in 1.0.2
