### ISSUE TITLE
Deep L - Transalation failed, request failed status 400 [BUG]

### ISSUE THREAD

**Issue by satrman1** [twentytwokhz/language-translator#11]
Deep L set properly (api key) - Test button is green, however if I open transaltion pane and try any transaltion, app says: Transalation failed, request failed status 400

**Comment by Fevol** [comment]
Hey @satrman1, I may be wrong, but I think that the issue you're describing is related to a different plugin - possibly mine. Could you check if that is in fact the case?

**Comment by satrman1** [comment]
Yeap, sorry about that. Closing

**Comment by Fevol** [comment]
No worries! By the way, are you still encountering the bug? If so,  please do open up an issue [here](https://github.com/fevol/obsidian-translate), so we can discuss it further. 

At my end the DeepL service, but there might be bug that I'm not aware of.
