### ISSUE TITLE
The operation is not allowed because the subscription has exceeded its free quota.

### ISSUE THREAD

**Issue by GitSteeK** [twentytwokhz/language-translator#16]
Hi, since today i got "The operation is not allowed because the subscription has exceeded its free quota." as result.

**Comment by valenzine** [comment]
Have you checked your Azure quota?

**Comment by twentytwokhz** [comment]
This is expected behavior as mentioned in the README:

`It's based on a free instance of Azure Translator. Please do not abuse it :)`
