### ISSUE TITLE
[BUG] failed to fetch

### ISSUE THREAD

**Issue by carloshenrique1985** [twentytwokhz/language-translator#18]
**Describe the bug**
ctrl + shift + R does not work in obsidian

**To Reproduce**
1-open obsidian
2-take a text in a language other than your own
3-select the text you want to translate
4-use the command Ctrl+Shift+R
5-the message "failed to fetch" appears in the top right corner
6-the selected text is deleted and not translated

**Expected behavior**
the text should change to the language I chose as the target

**Screenshots**
![image](https://github.com/twentytwokhz/language-translator/assets/160374567/accd22f8-f701-46ef-b351-c00816f3f4cf)

**Comment by twentytwokhz** [comment]
Issue now resolved with latest release
