### ISSUE TITLE
[FR] Different Translation providers

### ISSUE THREAD

**Issue by joethei** [twentytwokhz/language-translator#3]
How about adding support for different apis like
[LibreTranslate](https://github.com/LibreTranslate/LibreTranslate) which can be selfhosted.

**Comment by ORBITINGninja** [comment]
This one is probably best: https://www.deepl.com/

**Comment by joethei** [comment]
There is another translation plugin currently in development, which does support multiple providers:
Including LibreTranslate and DeepL: <https://github.com/Fevol/obsidian-translate>

**Comment by ORBITINGninja** [comment]
that's great! thx for info. i'm trying to solve dual language notes :)
