### ISSUE TITLE
[FR] API

### ISSUE THREAD

**Issue by joethei** [twentytwokhz/language-translator#4]
Provide a API to allow other plugins to translate text.

See this feature request in my plugin RSS Reader https://github.com/joethei/obsidian-rss/issues/56

**Comment by twentytwokhz** [comment]
I'd be more than happy to help with this feature.
Are you aware of ways this can be achieved with the obsidian plugin api?

I found only this [thread](https://forum.obsidian.md/t/inter-plugin-communication-expose-api-to-other-plugins/23618/4)

**Comment by joethei** [comment]
A simple way would be to expose a some methods in your plugins main class.
I do something similar in the [Text to speech](https://github.com/joethei/obsidian-tts) plugin.

Or you could do something like aidenlx does [here](https://github.com/aidenlx/obsidian-icon-shortcodes) which is create some typings and publish them.

Both methods are not that ideal, but as seen in the thread you linked, there is no official way yet.

**Comment by twentytwokhz** [comment]
I believe this was closed by mistake. Reopened
