### ISSUE TITLE
Unable to activate the plugin

### ISSUE THREAD

**Issue by ooker777** [twentytwokhz/language-translator#5]
Here is the console message:
```
Plugin failure: language-translator Error: ENOENT: no such file or directory, open 'D:\Quả Cầu\Dự án hỗ trợ\Knowhere\Obsidian\.obsidian\plugins\language-translator\main.js'
```

**Comment by twentytwokhz** [comment]
Please provide some reproduction steps.
When does this happen, how does this happen?
I tried using different folder paths and could not reproduce

**Comment by twentytwokhz** [comment]
Closed this by mistake. Reopening

**Comment by ooker777** [comment]
I'm not sure. It was for a past project and I don't need to work on it anymore. If I meet this problem again, I'll report it

**Comment by twentytwokhz** [comment]
Cool, thank you
